@echo off
REM ============================================================================
REM Jan Document Plugin - Windows Installer
REM ============================================================================
REM This script will:
REM   1. Check/install Python
REM   2. Create virtual environment
REM   3. Install Python dependencies
REM   4. Install Tesseract OCR (portable)
REM   5. Create desktop shortcut (optional)
REM ============================================================================

setlocal EnableDelayedExpansion

echo.
echo ========================================================================
echo    Jan Document Plugin - Windows Installer v1.0.0
echo ========================================================================
echo.

REM Get the directory where this script is located
set "INSTALL_DIR=%~dp0"
cd /d "%INSTALL_DIR%"

echo Install directory: %INSTALL_DIR%
echo.

REM ============================================================================
REM Check Python Installation
REM ============================================================================
echo [1/5] Checking Python installation...

where python >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo.
    echo ERROR: Python not found!
    echo.
    echo Please install Python 3.10 or later from:
    echo   https://www.python.org/downloads/
    echo.
    echo Make sure to check "Add Python to PATH" during installation.
    echo.
    pause
    exit /b 1
)

REM Check Python version
for /f "tokens=2 delims= " %%v in ('python --version 2^>^&1') do set PYVER=%%v
echo   Found Python %PYVER%

REM ============================================================================
REM Create Virtual Environment
REM ============================================================================
echo.
echo [2/5] Creating virtual environment...

if exist "venv" (
    echo   Virtual environment already exists, skipping...
) else (
    python -m venv venv
    if %ERRORLEVEL% NEQ 0 (
        echo ERROR: Failed to create virtual environment
        pause
        exit /b 1
    )
    echo   Created virtual environment
)

REM Activate virtual environment
call venv\Scripts\activate.bat

REM ============================================================================
REM Install Python Dependencies
REM ============================================================================
echo.
echo [3/5] Installing Python dependencies...
echo   This may take a few minutes on first run...
echo.

pip install --upgrade pip >nul 2>nul
pip install -r requirements.txt

if %ERRORLEVEL% NEQ 0 (
    echo.
    echo ERROR: Failed to install dependencies
    echo Try running: pip install -r requirements.txt
    pause
    exit /b 1
)

echo   Dependencies installed successfully

REM ============================================================================
REM Setup Tesseract OCR
REM ============================================================================
echo.
echo [4/5] Setting up Tesseract OCR...

set "TESSERACT_DIR=%INSTALL_DIR%tesseract"
set "TESSERACT_EXE=%TESSERACT_DIR%\tesseract.exe"

if exist "%TESSERACT_EXE%" (
    echo   Tesseract already installed in package
) else (
    echo.
    echo   Tesseract OCR needs to be downloaded.
    echo.
    echo   Please download Tesseract manually:
    echo   1. Go to: https://github.com/UB-Mannheim/tesseract/wiki
    echo   2. Download: tesseract-ocr-w64-setup-5.3.3.20231005.exe (or latest)
    echo   3. Run installer and install to: %TESSERACT_DIR%
    echo      OR install to default location and we'll detect it
    echo.
    echo   Alternatively, run this after installation completes:
    echo   winget install UB-Mannheim.TesseractOCR
    echo.
    
    REM Check common install locations
    if exist "C:\Program Files\Tesseract-OCR\tesseract.exe" (
        echo   Found system Tesseract at: C:\Program Files\Tesseract-OCR
        set "TESSERACT_EXE=C:\Program Files\Tesseract-OCR\tesseract.exe"
    )
)

REM ============================================================================
REM Download Embedding Model (First Run)
REM ============================================================================
echo.
echo [5/5] Pre-downloading embedding model...
echo   This happens once and may take 1-2 minutes...
echo.

python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('all-MiniLM-L6-v2'); print('  Model downloaded successfully')"

if %ERRORLEVEL% NEQ 0 (
    echo   Warning: Could not pre-download model. It will download on first use.
)

REM ============================================================================
REM Create Configuration File
REM ============================================================================
echo.
echo Creating configuration...

(
echo # Jan Document Plugin Configuration
echo # Generated by installer
echo.
echo TESSERACT_PATH=%TESSERACT_EXE%
echo PROXY_PORT=1338
echo JAN_PORT=1337
echo STORAGE_DIR=.\jan_doc_store
echo EMBEDDING_MODEL=all-MiniLM-L6-v2
echo AUTO_INJECT=true
echo MAX_CONTEXT_TOKENS=8000
) > config.env

echo   Configuration saved to config.env

REM ============================================================================
REM Installation Complete
REM ============================================================================
echo.
echo ========================================================================
echo    Installation Complete!
echo ========================================================================
echo.
echo To start the Jan Document Plugin:
echo.
echo   1. Make sure Jan is running with Local API Server enabled
echo      (Jan Settings -^> Local API Server -^> Enable)
echo.
echo   2. Double-click: JanDocumentPlugin.exe
echo      Or run: start_proxy.bat
echo.
echo   3. Upload documents via the web interface or API:
echo      http://localhost:1338
echo.
echo ========================================================================
echo.

pause
